feat(build): #1108 document contributing
fluidattacks/makes pull request #1111
Opened 2023-06-16 20:37 UTC by rohaquinlop

Add new sections to the contributing.md file to help newcomers.

- Running your local changes
- Adding yourself to the mailmap
- Validating commit message
- DCO
- Adding and rendering documentation

2023-06-16 21:00 UTC, rohaquinlop commented
@dsalaza4 I don't understand why I'm getting an error when building `/lintMarkdown/all`

log:
```
error: builder for '/nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv' failed with exit code 1;
       last 10 log lines:
       > MD013 warning: Parameter :code_blocks is deprecated.
       >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
       > MD013 warning: Parameter :code_blocks is deprecated.
       >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
       > MD013 warning: Parameter :code_blocks is deprecated.
       >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
       > MD013 warning: Parameter :code_blocks is deprecated.
       >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
       > MD013 warning: Parameter :code_blocks is deprecated.
       >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
       For full logs, run 'nix-store -l /nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv'.
```

2023-06-16 22:27 UTC, dsalaza4 commented
> @dsalaza4 I don't understand why I'm getting an error when building `/lintMarkdown/all`
> 
> log:
> 
> ```
> error: builder for '/nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv' failed with exit code 1;
>        last 10 log lines:
>        > MD013 warning: Parameter :code_blocks is deprecated.
>        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
>        > MD013 warning: Parameter :code_blocks is deprecated.
>        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
>        > MD013 warning: Parameter :code_blocks is deprecated.
>        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
>        > MD013 warning: Parameter :code_blocks is deprecated.
>        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
>        > MD013 warning: Parameter :code_blocks is deprecated.
>        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
>        For full logs, run 'nix-store -l /nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv'.
> ```

Good catch!

It looks like our lintMarkdown is outdated: https://github.com/fluidattacks/makes/blob/97ccd846a35e400a2784f4c4bcf2851272514c66/test/lint-markdown/config.rb#L12

2023-06-16 22:28 UTC, rohaquinlop commented
> > @dsalaza4 I don't understand why I'm getting an error when building `/lintMarkdown/all`
> > log:
> > ```
> > error: builder for '/nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv' failed with exit code 1;
> >        last 10 log lines:
> >        > MD013 warning: Parameter :code_blocks is deprecated.
> >        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
> >        > MD013 warning: Parameter :code_blocks is deprecated.
> >        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
> >        > MD013 warning: Parameter :code_blocks is deprecated.
> >        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
> >        > MD013 warning: Parameter :code_blocks is deprecated.
> >        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
> >        > MD013 warning: Parameter :code_blocks is deprecated.
> >        >   Please replace \":code_blocks => false\" by \":ignore_code_blocks => true\" in your configuration.
> >        For full logs, run 'nix-store -l /nix/store/kanp5drhji7a6whqqmpdq89dc08jldpx-lint-markdown-for-all.drv'.
> > ```
> 
> Good catch!
> 
> It looks like our `lintMarkdown` config is outdated:
> 
> https://github.com/fluidattacks/makes/blob/97ccd846a35e400a2784f4c4bcf2851272514c66/test/lint-markdown/config.rb#L12

Thank you, I'm gonna try updating it!

2023-06-16 23:20 UTC, dsalaza4 requested changes

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +any error message, if you do, then keep working, you're almost there!
```suggestion
- You can run local changes by simply running `m . <job>`.
- If you're adding new files, make sure to `git add` them so Makes can recognize them.
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +When contributing is important to add yourself to the `.mailmap` file.
```suggestion
- When contributing is important to add yourself to the [.mailmap](https://github.com/fluidattacks/makes/blob/main/.mailmap) file.
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +This file is lexicographically sorted, so you must to add you with this in mind.
```suggestion
- Make sure to test it with `m . /lintGitMailMap`.
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +You can test it running `m . /lintGitMailMap`.
```suggestion
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +have the proper structure with `m . /lintGitCommitMsg`.
```suggestion
- Your commit message must follow this [syntax](https://github.com/fluidattacks/makes/tree/main/test/lint-commit-msg).
- You can take a look at other commits [here](https://github.com/fluidattacks/makes/commits/main).
- Make sure to test it with `m . /lintGitCommitMsg`.
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +Contributors sign-off that they adhere to these requirements by adding a
```suggestion
You must sign your commits by adding a
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +`Signed-off-by` line to commit messages.
```suggestion
`Signed-off-by` line at the end of your commit message.
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +
```suggestion

Example:

```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +Signed-off-by: Full Name <email>
```suggestion
Signed-off-by: Robin Quintero <rohaquinlop301@gmail.com>
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +`.mailmap` file information.
```suggestion
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +### Adding and rendering documentation
```suggestion
### Rendering docs
```

2023-06-16 23:20 UTC, dsalaza4 commented on docs/src/contributing.md
> +When contributing in documentation use `m . /docs/dev` to render it.
```suggestion
You can run `m . /docs/dev` to serve the [doc site](https://makes.fluidattacks.com) on localhost.
```

2023-06-16 23:22 UTC, dsalaza4 commented
```md
### Other PR rules

A PR:

- Should only be one commit ahead of master
- Should have a title and body equal to the commit message
```

2023-06-16 23:24 UTC, dsalaza4 commented on docs/src/api/extensions/others.md
Unnecessary changes?

Maybe your editor automatically formatted the file?

2023-06-17 00:07 UTC, rohaquinlop commented on docs/src/api/extensions/others.md
No, I had to modify it because I was getting error when running `/lintMarkdown/all`, the errors were about the line length.

2023-06-17 01:37 UTC, dsalaza4 commented on docs/src/contributing.md
> +This is my commit message
Maybe add an entire commit message example including title and body?

2023-06-17 01:38 UTC, dsalaza4 commented on docs/src/contributing.md
> +All added features must be commented in the same PR.
```suggestion
All added features must be documented in the same PR.
```

2023-06-17 01:43 UTC, dsalaza4 commented on docs/src/contributing.md
> +When contributing is important to add yourself to the
```suggestion
When contributing it is important to add yourself to the
```

2023-06-17 01:43 UTC, dsalaza4 commented on docs/src/contributing.md
> +commit messages.
```suggestion
commit message.
```

2023-06-17 01:43 UTC, dsalaza4 commented on docs/src/contributing.md
> +All added features must be documented in the same PR.
```suggestion
All changes must be documented in the same PR.
```

2023-06-17 01:44 UTC, dsalaza4 commented on docs/src/contributing.md
> +feat(build): #1099 licensing builtin with reuse
I actually like this one even more! ❤️

2023-06-17 01:46 UTC, dsalaza4 commented on docs/src/contributing.md
> +them.
```suggestion
If you're adding new files, make sure to `git add` first.
```

2023-06-17 01:46 UTC, rohaquinlop commented on docs/src/contributing.md
> +feat(build): #1099 licensing builtin with reuse
Niceee, thanks!

2023-06-17 01:49 UTC, dsalaza4 commented on docs/src/contributing.md
> +If you're adding new files, make sure `git add` first.
```suggestion
If you're adding new files, make sure `git add` them first.
```

2023-06-17 01:52 UTC, dsalaza4 commented on docs/src/contributing.md
> +on localhost.
```suggestion
- All changes must be documented in the same PR.
- You can run `m . /docs/dev` to serve the [doc site](https://makes.fluidattacks.com)
on localhost.
- Make sure to lint the documentation with `m . /lintMarkdown/all`.
```

2023-06-17 02:00 UTC, dsalaza4 requested changes

2023-06-17 02:00 UTC, dsalaza4 commented on docs/src/contributing.md
> +If you're adding new files, make sure `git add` them first.
```suggestion
If you're adding new files, make sure to `git add` them first.
```

2023-06-17 02:00 UTC, dsalaza4 commented on docs/src/contributing.md
> +When contributing it is important to add yourself to the
```suggestion
You must add yourself to the
```

2023-06-17 02:00 UTC, dsalaza4 commented on docs/src/contributing.md
> +- You can run `m . /docs/dev` to serve the [doc site](https://makes.fluidattacks.com)
```suggestion
- You can run `m . /docs/dev` to serve the [docs site](https://makes.fluidattacks.com).
```

2023-06-17 02:00 UTC, dsalaza4 commented on docs/src/contributing.md
> +- Make sure to lint the documentation with `m . /lintMarkdown/all`
```suggestion
- Make sure you lint the documentation with `m . /lintMarkdown/all`.
```

2023-06-17 02:00 UTC, dsalaza4 commented
@rohaquinlop We're almost there! 🚀

2023-06-17 02:08 UTC, dsalaza4 commented
Move current `Examples:` to a `### Examples` section below `### Other PR Rules`

2023-06-17 02:09 UTC, dsalaza4 commented on docs/src/contributing.md
> +### DCO
```suggestion
### Signing your commit
```

2023-06-17 02:11 UTC, dsalaza4 commented
Remove Guidelines section

2023-06-17 02:12 UTC, rohaquinlop commented
> Remove Guidelines section

The whole items?

2023-06-17 02:19 UTC, dsalaza4 commented
```md
### Testing new features

- All new [builtins](https://makes.fluidattacks.com/api/builtins/)
must be tested.
- You can add tests to either `/makes.nix` or `/makes/your-builtin/main.nix` depending on the nature of the builtin.
- Make sure to add such tests to the [GitHub Actions pipelines as well](https://github.com/fluidattacks/makes/tree/main/.github/workflows).
```

2023-06-17 02:20 UTC, dsalaza4 commented
> > Remove Guidelines section
> 
> The whole items?

Yes, the entire section

2023-06-17 02:23 UTC, dsalaza4 commented
Order:

1. Testing your local changes
2. Adding documentation
3. Testing new features
4. Adding yourself to the mailmap
6. Validating commit message (Remove `signing your commit`, add extra item here)
7. Other PR Rules
8. Examples

2023-06-17 02:26 UTC, dsalaza4 requested changes

2023-06-17 02:26 UTC, dsalaza4 commented on docs/src/contributing.md
> +- Make sure to test it with `m . /lintGitCommitMsg`.
```suggestion
- Your commit message must follow this [syntax](https://github.com/fluidattacks/makes/tree/main/test/lint-commit-msg).
- You must sign your commits by adding a `Signed-off-by` line at the end of your
commit message.
- You can take a look at other commits [here](https://github.com/fluidattacks/makes/commits/main).
- Make sure to test it with `m . /lintGitCommitMsg`.
```

2023-06-17 02:27 UTC, dsalaza4 commented
Rename `Testing new features` to `Adding tests`

2023-06-17 02:32 UTC, dsalaza4 requested changes

2023-06-17 02:32 UTC, dsalaza4 commented on docs/src/contributing.md
> +- Make sure you lint the documentation with `m . /lintMarkdown/all`
```suggestion
- Make sure you lint the documentation with `m . /lintMarkdown/all`.
```

2023-06-17 02:32 UTC, dsalaza4 commented on docs/src/contributing.md
> +```
Remove this. Unnecessary as we're already pointing to example commit messages.

2023-06-17 02:32 UTC, dsalaza4 commented on docs/src/contributing.md
> +Code contributions:
```suggestion
```

2023-06-17 02:33 UTC, dsalaza4 commented
Rename `Validating commit message` to `Writing a valid commit message`.

2023-06-17 02:43 UTC, dsalaza4 commented
Move everything under a guidelines section:

```md
## Code contributions

We accept anything that benefits the community,
thanks for sharing your work with the world.
We can discuss implementation details [here][makes_issues].

### Guidelines

1. Write your idea: [here][makes_issues]
1. Fork [Makes on GitHub][makes]
1. [Git][git]-clone your fork
1. Hack as much as you like!
1. [Git][git]-commit your changes.
1. [Git][git]-push changes to your fork
1. Create a **Pull Request** from your fork to [Makes][makes]

#### Testing your local changes

(...)

#### Adding documentation

(...)

#### Examples

(...)

### The legal side of contributions

(...)
```

2023-06-17 02:50 UTC, dsalaza4 requested changes

2023-06-17 02:50 UTC, dsalaza4 commented on docs/src/contributing.md
> +- Make sure to add such tests to the [GitHub Actions pipelines as well](https://github.com/fluidattacks/makes/tree/main/.github/workflows).
```suggestion
- Make sure to add such tests 
  to the [GitHub Actions pipelines](https://github.com/fluidattacks/makes/tree/main/.github/workflows) 
  as well.
```

2023-06-17 02:54 UTC, dsalaza4 commented on docs/src/contributing.md
> +  to the [GitHub Actions pipelines as well](https://github.com/fluidattacks/makes/tree/main/.github/workflows)
```suggestion
  to the [GitHub Actions pipelines](https://github.com/fluidattacks/makes/tree/main/.github/workflows)
```

2023-06-17 03:01 UTC, dsalaza4 approved these changes

2023-06-17 03:02 UTC, dsalaza4 commented
LGTM! Merging! Thank you so much for this contribution!

2023-06-17 03:02 UTC, merged