feat(build): #990 move cache directory
fluidattacks/makes pull request #1116
Opened 2023-06-24 13:22 UTC by sebas031811

2023-06-26 19:05 UTC, dsalaza4 commented
Hi @sebas031811,

Thank you so much for your contribution!

I see other files that also reference the `.makes` folder:

https://github.com/fluidattacks/makes/blob/3004ae797b2ed44806cb9d923d0c4b293dd93c37/src/args/agnostic.nix#L5-L6

https://github.com/fluidattacks/makes/blob/3004ae797b2ed44806cb9d923d0c4b293dd93c37/src/evaluator/modules/default.nix#L62

2023-06-26 19:21 UTC, sebas031811 commented
Hi @dsalaza4,  
I understood it was just '.makes/cache'. Anyway, there is also a file 'demo.svg', how could I change it?

2023-06-26 23:20 UTC, dsalaza4 commented
@sebas031811 Everything should be under `.cache/makes` now. 

Regarding the demo, you can leave it the way it is.

2023-06-26 23:22 UTC, dsalaza4 requested changes

2023-06-26 23:22 UTC, dsalaza4 commented on src/args/agnostic.nix
> +    project = "$HOME_IMPURE/.cache/state/__default__";
```suggestion
    global = "$HOME_IMPURE/.cache/makes/state";
    project = "$HOME_IMPURE/.cache/makes/state/__default__";
```

2023-06-26 23:22 UTC, dsalaza4 commented on docs/src/api/extensions/fundamentals.md
> +        /home/user/.cache/state/example
```suggestion
        /home/user/.cache/makes/state/example
```

2023-06-26 23:22 UTC, dsalaza4 commented on docs/src/api/extensions/fundamentals.md
> +        [INFO] Running tree command on /home/user/.cache/state/example
```suggestion
        [INFO] Running tree command on /home/user/.cache/makes/state/example
```

2023-06-26 23:22 UTC, dsalaza4 commented on src/cli/main/cli.py
> +MAKES_DIR: str = join(environ["HOME_IMPURE"], ".cache")
```suggestion
MAKES_DIR: str = join(environ["HOME_IMPURE"], ".cache/makes")
```

2023-06-26 23:22 UTC, dsalaza4 commented on src/cli/main/cli.py
> +makedirs(join(MAKES_DIR, "makes"), exist_ok=True)
```suggestion
makedirs(MAKES_DIR), exist_ok=True)
```

2023-06-26 23:22 UTC, dsalaza4 commented on src/cli/main/cli.py
> +SOURCES_CACHE: str = join(MAKES_DIR, "makes", "sources")
```suggestion
SOURCES_CACHE: str = join(MAKES_DIR, "sources")
```

2023-06-26 23:22 UTC, dsalaza4 commented on src/evaluator/modules/default.nix
> +      default = "$HOME_IMPURE/.cache/state";
```suggestion
      default = "$HOME_IMPURE/.cache/makes/state";
```

2023-06-27 01:08 UTC, dsalaza4 commented
Please resolve previous threads accordingly

2023-06-27 19:34 UTC, dsalaza4 commented
@sebas031811 

Calling the TUI with `m .` and then selection a job seems to be failing after installing your CLI version with `nix-env -if .`.

To reproduce:

1. Install your cli with `nix-env -if .`
2. Run any makes job from the TUI by running `m .` first and then selecting a job.

2023-06-27 19:37 UTC, dsalaza4 commented
> @sebas031811
> 
> Calling the TUI with `m .` and then selection a job seems to be failing after installing your CLI version with `nix-env -if .`.
> 
> To reproduce:
> 
> 1. Install your cli with `nix-env -if .`
> 2. Run any makes job from the TUI by running `m .` first and then selecting a job.

I think it has to do with having an unnecessary second level `cache` directory here: 

https://github.com/fluidattacks/makes/blob/3004ae797b2ed44806cb9d923d0c4b293dd93c37/src/cli/main/cli.py#L547

2023-06-27 19:57 UTC, dsalaza4 approved these changes
LGTM!

2023-06-27 19:57 UTC, merged